Repository KnightHacks/knighthacks_users, pull requests merged in 2022-06, with the labels that each got.

#1 test
  .github/workflows/check.yml
  test
Labels: patch

#4 Revert "added version tag"
  .github/workflows/release.yml
Labels: patch

#5 Revert "Revert "added version tag""
  .github/workflows/release.yml
Labels: patch

#6 added 'v' prefix to tag
  .github/workflows/release.yml
Labels: patch

#7 release job & compile checking
  .github/workflows/release.yml
Labels: major

#8 test
  test
Labels: patch

#9 deleted test file
  test
Labels: patch

#14 JWT Authentication
  go.mod
  go.sum
  graph/entity.resolvers.go
  graph/generated/federation.go
  graph/generated/generated.go
  graph/model/models_gen.go
  graph/schema.graphqls
  graph/schema.resolvers.go
  main.go
  repository/database_repository.go
  repository/repository.go
Labels: minor

#16 Version 1.0.0
  go.mod
  go.sum
  graph/entity.resolvers.go
  graph/generated/federation.go
  graph/generated/generated.go
  graph/model/models_gen.go
  graph/schema.graphqls
  graph/schema.resolvers.go
  main.go
  repository/database_repository.go
  repository/repository.go
Labels: enhancement, major

#18 Revert "Revert "Version 1.0.0""
  go.mod
  go.sum
  graph/entity.resolvers.go
  graph/generated/federation.go
  graph/generated/generated.go
  graph/model/models_gen.go
  graph/schema.graphqls
  graph/schema.resolvers.go
  main.go
  repository/database_repository.go
  repository/repository.go
Labels: major

#19 fixed accidentally broken reference to shared@main
  go.mod
  go.sum
Labels: patch

#12 implemented updateUser in database repository
  graph/schema.resolvers.go
  repository/database_repository.go
  repository/repository.go
Labels: minor
